var N = null;var sourcesIndex = {};
sourcesIndex["owlc_cli"] = {"name":"","files":["main.rs"]};
sourcesIndex["owlc_driver"] = {"name":"","files":["lib.rs"]};
sourcesIndex["owlc_error"] = {"name":"","files":["lib.rs"]};
sourcesIndex["owlc_lexer"] = {"name":"","files":["lexer.rs","lib.rs","token.rs"]};
sourcesIndex["owlc_llvm"] = {"name":"","files":["lib.rs","macros.rs"]};
sourcesIndex["owlc_parser"] = {"name":"","dirs":[{"name":"ast","files":["expressions.rs","statements.rs"]}],"files":["ast.rs","lib.rs","parser.rs","visitor.rs"]};
sourcesIndex["owlc_passes"] = {"name":"","files":["fn_main.rs","lib.rs","resolver.rs"]};
sourcesIndex["owlc_source"] = {"name":"","files":["lib.rs"]};
sourcesIndex["owlc_span"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
