[package]
authors = ["Luke Chu <lukechu10@users.noreply.github.com>"]
edition = "2018"
name = "owlc-error"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.0"
owlc-span = {path = "../owlc-span"}
