on: [push]

name: Rust

jobs:
  coverage:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install LLVM 10
        run: sudo apt-get install libllvm10 llvm-10 llvm-10-dev llvm-10-runtime

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.14.3'
          args: '-- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: cobertura.xml
