name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM 10
      run: sudo apt-get install libllvm10 llvm-10 llvm-10-dev llvm-10-runtime

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
    
    - name: Build documentation
      run: cargo doc --no-deps

    - name: Create .nojekyll file
      run: touch target/doc/.nojekyll
        
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.7.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh_pages
        force_orphan: true
        publish_dir: target/doc/
        enable_jekyll: false
