name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM 10
      run: sudo apt-get install libllvm10 llvm-10 llvm-10-dev llvm-10-runtime
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
